### ISSUE TITLE
`meta` class in highlight

### ISSUE THREAD

**Issue by qiankanglai** [viosey/hexo-theme-material#427]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

It seems highlight is conflicting with hexo-theme-material's own stylesheets

![image](https://user-images.githubusercontent.com/1546130/27939590-8008cb44-62f8-11e7-9808-50fa4ba08679.png)

`@Override` has class named `meta` but it is also used in material/source/css/style.css, leaving a strange display

**Comment by neoFelhz** [comment]
Please read the docs carefully.
We have already told you that you shouldn't Use highlight.js the hexo built in to color the code. You should use `hexo-prism-plugin` instead.

READ THE FUCKING MANUALS !!!!
